# Generated by Django 5.0.6 on 2024-06-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.CharField(
                blank=True,
                help_text="Введите дату",
                max_length=100,
                null=True,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
